server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5434/squad_prod
spring.datasource.username=${DB_USERNAME_PROD}
spring.datasource.password=${DB_PASSWORD_PROD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.flyway.enabled=true
cors.allowed-origins=http://localhost:5173
logging.file.name=/opt/homebrew/var/log/404/dev.log
