server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5433/squad_staging
spring.datasource.username=${DB_USERNAME_STAGING}
spring.datasource.password=${DB_PASSWORD_STAGING}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true
cors.allowed-origins=http://localhost:5173
logging.file.name=/opt/homebrew/var/log/404/dev.log
