spring.datasource.url=jdbc:postgresql://localhost:5434/futza_prod
spring.datasource.username=${DB_USERNAME_PROD}
spring.datasource.password=${DB_PASSWORD_PROD}
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.jpa.show-sql=false
server.port=8084
logging.file.name=/opt/homebrew/var/log/404/prod-be.log
cors.allowed-origins=${CORS_ALLOWED_ORIGINS}
