-- ============================================================
-- V20260101_00_00_00: Full schema init
-- Replaces V1 (data migration) + V2 (ALTER TABLE baseline).
-- Idempotent: CREATE TABLE/SEQUENCE IF NOT EXISTS.
-- Constraints wrapped in exception-safe DO blocks.
-- Envers audit tables are handled separately in V20260312.
-- ============================================================

-- Function
CREATE OR REPLACE FUNCTION public.update_player_ratings() RETURNS void
    LANGUAGE plpgsql AS $$
BEGIN
    UPDATE player p
    SET rating = (SELECT AVG(r.rating) FROM roster r WHERE r.player_id = p.id)
    WHERE EXISTS (SELECT 1 FROM roster r WHERE r.player_id = p.id);
END;
$$;

-- ============================================================
-- SEQUENCES (old-style — used by game, player, roster, etc.)
-- ============================================================
CREATE SEQUENCE IF NOT EXISTS public.game_id_seq         AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.game_location_id_seq AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.goal_id_seq         AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.player_id_seq       AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.player_persona_id_seq        START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.rating_id_seq       AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.roster_id_seq       AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.roster_persona_id_seq        START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.user_id_seq         AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.revinfo_id_seq               START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

-- ============================================================
-- CORE TABLES
-- ============================================================

CREATE TABLE IF NOT EXISTS public."user" (
    id                  integer      NOT NULL DEFAULT nextval('public.user_id_seq'),
    created_at          timestamp(6) NOT NULL,
    password            character varying(255) NOT NULL,
    role                character varying(255) NOT NULL,
    username            character varying(255) NOT NULL,
    player_id           integer,
    is_super_admin      boolean      NOT NULL DEFAULT false,
    updated_at          timestamp(6),
    created_by_user_id  integer,
    updated_by_user_id  integer,
    active              boolean      NOT NULL DEFAULT true
);
ALTER SEQUENCE public.user_id_seq OWNED BY public."user".id;

CREATE TABLE IF NOT EXISTS public.squad (
    id                  integer      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at          timestamp(6) NOT NULL,
    invite_code         character varying(8) NOT NULL,
    name                character varying(255) NOT NULL,
    created_by_user_id  integer,
    updated_at          timestamp(6),
    updated_by_user_id  integer,
    owner_user_id       integer,
    active              boolean      NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.player (
    id                  integer      NOT NULL DEFAULT nextval('public.player_id_seq'),
    active              boolean      NOT NULL,
    foot                character varying(255) DEFAULT NULL,
    name                character varying(255) DEFAULT NULL,
    photo               character varying(255) DEFAULT NULL,
    "position"          character varying(255) DEFAULT NULL,
    rating              double precision,
    surname             character varying(255) DEFAULT NULL,
    squad_id            integer,
    created_at          timestamp(6),
    updated_at          timestamp(6),
    created_by_user_id  integer,
    updated_by_user_id  integer
);
ALTER SEQUENCE public.player_id_seq OWNED BY public.player.id;

CREATE TABLE IF NOT EXISTS public.game_location (
    id                  integer      NOT NULL DEFAULT nextval('public.game_location_id_seq'),
    location            character varying(255) DEFAULT NULL,
    address             character varying(255) DEFAULT NULL,
    latitude            double precision,
    longitude           double precision,
    squad_id            integer,
    created_at          timestamp(6),
    updated_at          timestamp(6),
    created_by_user_id  integer,
    updated_by_user_id  integer,
    active              boolean      NOT NULL DEFAULT true
);
ALTER SEQUENCE public.game_location_id_seq OWNED BY public.game_location.id;

CREATE TABLE IF NOT EXISTS public.game (
    id                  integer      NOT NULL DEFAULT nextval('public.game_id_seq'),
    away_team_score     integer,
    date_time           timestamp(6) NOT NULL,
    home_team_score     integer,
    is_played           boolean      NOT NULL,
    is_voted            boolean      NOT NULL,
    location            character varying(255) NOT NULL,
    weather             character varying(255) NOT NULL,
    game_location_id    integer,
    mvp_id              integer,
    squad_id            integer,
    created_at          timestamp(6),
    updated_at          timestamp(6),
    created_by_user_id  integer,
    updated_by_user_id  integer,
    active              boolean      NOT NULL DEFAULT true
);
ALTER SEQUENCE public.game_id_seq OWNED BY public.game.id;

CREATE TABLE IF NOT EXISTS public.roster (
    id                  integer      NOT NULL DEFAULT nextval('public.roster_id_seq'),
    rating              double precision,
    team_color          character varying(255) NOT NULL,
    game_id             integer      NOT NULL,
    player_id           integer      NOT NULL,
    persona1            integer,
    persona2            integer,
    persona3            integer,
    has_vote            boolean,
    created_at          timestamp(6),
    updated_at          timestamp(6),
    created_by_user_id  integer,
    updated_by_user_id  integer,
    active              boolean      NOT NULL DEFAULT true
);
ALTER SEQUENCE public.roster_id_seq OWNED BY public.roster.id;

CREATE TABLE IF NOT EXISTS public.goal (
    id                  integer      NOT NULL DEFAULT nextval('public.goal_id_seq'),
    team_color          character varying(255) NOT NULL,
    game_id             integer      NOT NULL,
    player_id           integer      NOT NULL,
    created_at          timestamp(6),
    updated_at          timestamp(6),
    created_by_user_id  integer,
    updated_by_user_id  integer,
    active              boolean      NOT NULL DEFAULT true
);
ALTER SEQUENCE public.goal_id_seq OWNED BY public.goal.id;

CREATE TABLE IF NOT EXISTS public.rating (
    id                  integer      NOT NULL DEFAULT nextval('public.rating_id_seq'),
    rate                integer      NOT NULL,
    player_id           integer,
    roster_id           integer,
    created_at          timestamp(6),
    updated_at          timestamp(6),
    created_by_user_id  integer,
    updated_by_user_id  integer,
    active              boolean      NOT NULL DEFAULT true
);
ALTER SEQUENCE public.rating_id_seq OWNED BY public.rating.id;

CREATE TABLE IF NOT EXISTS public.persona (
    id                  integer      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    category            character varying(255),
    description         character varying(255),
    name                character varying(255) NOT NULL,
    created_at          timestamp(6),
    updated_at          timestamp(6),
    created_by_user_id  integer,
    updated_by_user_id  integer,
    active              boolean      NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.player_persona (
    id                  integer      NOT NULL DEFAULT nextval('public.player_persona_id_seq'),
    count               integer      NOT NULL,
    persona_id          integer      NOT NULL,
    player_id           integer      NOT NULL,
    squad_id            integer,
    created_at          timestamp(6),
    updated_at          timestamp(6),
    created_by_user_id  integer,
    updated_by_user_id  integer,
    active              boolean      NOT NULL DEFAULT true
);
ALTER SEQUENCE public.player_persona_id_seq OWNED BY public.player_persona.id;

CREATE TABLE IF NOT EXISTS public.roster_persona (
    id                  integer      NOT NULL DEFAULT nextval('public.roster_persona_id_seq'),
    count               integer      NOT NULL,
    persona_id          integer      NOT NULL,
    roster_id           integer      NOT NULL,
    created_at          timestamp(6),
    updated_at          timestamp(6),
    created_by_user_id  integer,
    updated_by_user_id  integer,
    active              boolean      NOT NULL DEFAULT true
);
ALTER SEQUENCE public.roster_persona_id_seq OWNED BY public.roster_persona.id;

CREATE TABLE IF NOT EXISTS public.group_membership (
    id                  integer      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    joined_at           timestamp(6) NOT NULL,
    role                character varying(255) NOT NULL,
    player_id           integer      NOT NULL,
    squad_id            integer      NOT NULL,
    user_id             integer      NOT NULL,
    created_at          timestamp(6),
    updated_at          timestamp(6),
    created_by_user_id  integer,
    updated_by_user_id  integer,
    active              boolean      NOT NULL DEFAULT true,
    CONSTRAINT group_membership_role_check CHECK (role = ANY (ARRAY['ADMIN'::varchar, 'MEMBER'::varchar]))
);

CREATE TABLE IF NOT EXISTS public.join_request (
    id                  integer      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at          timestamp(6) NOT NULL,
    player_foot         character varying(255),
    player_name         character varying(255) NOT NULL,
    player_position     character varying(255),
    player_surname      character varying(255) NOT NULL,
    reviewed_at         timestamp(6),
    status              character varying(255) NOT NULL,
    reviewed_by_user_id integer,
    squad_id            integer      NOT NULL,
    user_id             integer      NOT NULL,
    updated_at          timestamp(6),
    created_by_user_id  integer,
    updated_by_user_id  integer,
    active              boolean      NOT NULL DEFAULT true,
    CONSTRAINT join_request_status_check CHECK (status = ANY (ARRAY['PENDING'::varchar, 'APPROVED'::varchar, 'REJECTED'::varchar]))
);

CREATE TABLE IF NOT EXISTS public.squad_request (
    id                  integer      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at          timestamp(6) NOT NULL,
    name                character varying(255) NOT NULL,
    player_foot         character varying(255),
    player_name         character varying(255),
    player_position     character varying(255),
    player_surname      character varying(255),
    reviewed_at         timestamp(6),
    status              character varying(255) NOT NULL,
    requested_by_user_id integer     NOT NULL,
    reviewed_by_user_id integer,
    updated_at          timestamp(6),
    created_by_user_id  integer,
    updated_by_user_id  integer,
    active              boolean      NOT NULL DEFAULT true,
    CONSTRAINT squad_request_status_check CHECK (status = ANY (ARRAY['PENDING'::varchar, 'APPROVED'::varchar, 'REJECTED'::varchar]))
);

-- ============================================================
-- PRIMARY KEYS (exception-safe)
-- ============================================================
DO $$ BEGIN ALTER TABLE public."user"          ADD CONSTRAINT user_pkey            PRIMARY KEY (id);           EXCEPTION WHEN duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.squad           ADD CONSTRAINT squad_pkey           PRIMARY KEY (id);           EXCEPTION WHEN duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.player          ADD CONSTRAINT player_pkey          PRIMARY KEY (id);           EXCEPTION WHEN duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.game_location   ADD CONSTRAINT game_location_pkey   PRIMARY KEY (id);           EXCEPTION WHEN duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.game            ADD CONSTRAINT game_pkey            PRIMARY KEY (id);           EXCEPTION WHEN duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.roster          ADD CONSTRAINT roster_pkey          PRIMARY KEY (id);           EXCEPTION WHEN duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.goal            ADD CONSTRAINT goal_pkey            PRIMARY KEY (id);           EXCEPTION WHEN duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.rating          ADD CONSTRAINT rating_pkey          PRIMARY KEY (id);           EXCEPTION WHEN duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.persona         ADD CONSTRAINT persona_pkey         PRIMARY KEY (id);           EXCEPTION WHEN duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.player_persona  ADD CONSTRAINT player_persona_pkey  PRIMARY KEY (id);           EXCEPTION WHEN duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.roster_persona  ADD CONSTRAINT roster_persona_pkey  PRIMARY KEY (id);           EXCEPTION WHEN duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.group_membership ADD CONSTRAINT group_membership_pkey PRIMARY KEY (id);         EXCEPTION WHEN duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.join_request    ADD CONSTRAINT join_request_pkey    PRIMARY KEY (id);           EXCEPTION WHEN duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.squad_request   ADD CONSTRAINT squad_request_pkey   PRIMARY KEY (id);           EXCEPTION WHEN duplicate_object OR invalid_table_definition THEN NULL; END $$;

-- ============================================================
-- UNIQUE CONSTRAINTS (exception-safe)
-- ============================================================
DO $$ BEGIN ALTER TABLE public."user"          ADD CONSTRAINT user_username_key    UNIQUE (username);                      EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.squad           ADD CONSTRAINT ukjkt2ck2m7ws6h01c0wh0rfyhu UNIQUE (invite_code);            EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.persona         ADD CONSTRAINT uks3eaqj445pebya5cn7gjxacfi UNIQUE (name);                  EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.player_persona  ADD CONSTRAINT uk844nmcxox0r4lmbfy7y0ka2x2 UNIQUE (player_id, persona_id);  EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.group_membership ADD CONSTRAINT uksai2jftk78wj9fsgps3hd9hcl UNIQUE (squad_id, user_id);    EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;

-- ============================================================
-- INDEXES (exception-safe)
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_join_request_user_squad_status ON public.join_request USING btree (user_id, squad_id, status);

-- ============================================================
-- FOREIGN KEYS (exception-safe)
-- ============================================================
DO $$ BEGIN ALTER TABLE public."user"           ADD CONSTRAINT fk_user_player           FOREIGN KEY (player_id)           REFERENCES public.player(id);           EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."user"           ADD CONSTRAINT fkjdbercrvbps41rsv8m8ebigvs FOREIGN KEY (created_by_user_id)  REFERENCES public."user"(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."user"           ADD CONSTRAINT fkrtfvsv770aj45r621ca6fy9h6 FOREIGN KEY (updated_by_user_id)  REFERENCES public."user"(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN ALTER TABLE public.squad            ADD CONSTRAINT fkaavedjau59vhe4coufig7ik2k FOREIGN KEY (created_by_user_id)  REFERENCES public."user"(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.squad            ADD CONSTRAINT fkcomidadbdwibftre0bnaglen  FOREIGN KEY (updated_by_user_id)  REFERENCES public."user"(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.squad            ADD CONSTRAINT fkthhhtrm8498e3uagxkjuh9xva FOREIGN KEY (owner_user_id)       REFERENCES public."user"(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN ALTER TABLE public.player           ADD CONSTRAINT fkg699nb6iet4925e35gbgjqu7o FOREIGN KEY (squad_id)           REFERENCES public.squad(id);           EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.player           ADD CONSTRAINT fk390pm7ti1uv9khqiyd6fqgdms FOREIGN KEY (created_by_user_id)  REFERENCES public."user"(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.player           ADD CONSTRAINT fk8wyvs3v9mufsv30ol33vrfx9v FOREIGN KEY (updated_by_user_id)  REFERENCES public."user"(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN ALTER TABLE public.game_location    ADD CONSTRAINT fknpq1191kqub82rimn2x4blsmq FOREIGN KEY (squad_id)           REFERENCES public.squad(id);           EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.game_location    ADD CONSTRAINT fka10ty9tr59k49eb4ht2fu0au6 FOREIGN KEY (created_by_user_id)  REFERENCES public."user"(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.game_location    ADD CONSTRAINT fklw1gwrtej60rxepe14j99b8ip FOREIGN KEY (updated_by_user_id)  REFERENCES public."user"(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN ALTER TABLE public.game             ADD CONSTRAINT fk2moyq5v34p3wfjlaxknlnoc5p FOREIGN KEY (squad_id)           REFERENCES public.squad(id);           EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.game             ADD CONSTRAINT fk_game_game_location        FOREIGN KEY (game_location_id)   REFERENCES public.game_location(id);   EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.game             ADD CONSTRAINT fkioi4q7d9e06mnxsp4i70wnef4 FOREIGN KEY (created_by_user_id)  REFERENCES public."user"(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.game             ADD CONSTRAINT fk5nni27qewngct5561piwqb2f2 FOREIGN KEY (updated_by_user_id)  REFERENCES public."user"(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN ALTER TABLE public.roster           ADD CONSTRAINT fk_roster_game               FOREIGN KEY (game_id)            REFERENCES public.game(id);            EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.roster           ADD CONSTRAINT fk_roster_player             FOREIGN KEY (player_id)          REFERENCES public.player(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.roster           ADD CONSTRAINT fk32x3qi8wai5vbxu141hkvuueq FOREIGN KEY (created_by_user_id)  REFERENCES public."user"(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.roster           ADD CONSTRAINT fkppm8ep6fxcopr8vogq0tgqi8  FOREIGN KEY (updated_by_user_id)  REFERENCES public."user"(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN ALTER TABLE public.goal             ADD CONSTRAINT fk_goal_game                 FOREIGN KEY (game_id)            REFERENCES public.game(id);            EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.goal             ADD CONSTRAINT fk_goal_player               FOREIGN KEY (player_id)          REFERENCES public.player(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.goal             ADD CONSTRAINT fk5cnqj0hjjtpj84wt8aejjphoo FOREIGN KEY (created_by_user_id)  REFERENCES public."user"(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.goal             ADD CONSTRAINT fk61o10ueafn8bjfjjumvg23tt0 FOREIGN KEY (updated_by_user_id)  REFERENCES public."user"(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN ALTER TABLE public.rating           ADD CONSTRAINT fk_rating_player             FOREIGN KEY (player_id)          REFERENCES public.player(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.rating           ADD CONSTRAINT fk_rating_roster             FOREIGN KEY (roster_id)          REFERENCES public.roster(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.rating           ADD CONSTRAINT fkafashagmypah8xfgaerwfc7vy FOREIGN KEY (created_by_user_id)  REFERENCES public."user"(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.rating           ADD CONSTRAINT fkip7wwcgerr0ieuwbpd6w2e6hd FOREIGN KEY (updated_by_user_id)  REFERENCES public."user"(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN ALTER TABLE public.persona          ADD CONSTRAINT fkkcqbakiilip3b5mbhldfd3h3f FOREIGN KEY (created_by_user_id)  REFERENCES public."user"(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.persona          ADD CONSTRAINT fkau7ecm1o5aiwkn3htxl5253tj FOREIGN KEY (updated_by_user_id)  REFERENCES public."user"(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN ALTER TABLE public.player_persona   ADD CONSTRAINT fk2l2b2v5pjglbyl3gm4rhud6ag FOREIGN KEY (player_id)          REFERENCES public.player(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.player_persona   ADD CONSTRAINT fk52y6nh0igvejys12uby0j6i30 FOREIGN KEY (persona_id)         REFERENCES public.persona(id);         EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.player_persona   ADD CONSTRAINT fkqypmuwveqjv1i4ib218o897rt FOREIGN KEY (squad_id)           REFERENCES public.squad(id);           EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.player_persona   ADD CONSTRAINT fk1gwmfn9hd2gv2692skp449e3t FOREIGN KEY (created_by_user_id)  REFERENCES public."user"(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.player_persona   ADD CONSTRAINT fker9uq1lruapmvlv6cxy2nbg83 FOREIGN KEY (updated_by_user_id)  REFERENCES public."user"(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN ALTER TABLE public.roster_persona   ADD CONSTRAINT fks5ox2ada39musrt5uxpn2qgtp FOREIGN KEY (roster_id)          REFERENCES public.roster(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.roster_persona   ADD CONSTRAINT fkdatfj8m6ck26qrgotwqteoj09 FOREIGN KEY (persona_id)         REFERENCES public.persona(id);         EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.roster_persona   ADD CONSTRAINT fk8hfts7d5i85y2m6abedhyvyix FOREIGN KEY (created_by_user_id)  REFERENCES public."user"(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.roster_persona   ADD CONSTRAINT fkfun7dchv2aai5ihu5053ok3y6 FOREIGN KEY (updated_by_user_id)  REFERENCES public."user"(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN ALTER TABLE public.group_membership ADD CONSTRAINT fkjlpcvq2uwf4ooo9djueafip3d FOREIGN KEY (squad_id)           REFERENCES public.squad(id);           EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.group_membership ADD CONSTRAINT fknjsm2sk498qbh2bkw58s00dg7 FOREIGN KEY (user_id)            REFERENCES public."user"(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.group_membership ADD CONSTRAINT fk8fa2tfh7rntsseppm4wnf05ju FOREIGN KEY (player_id)          REFERENCES public.player(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.group_membership ADD CONSTRAINT fktkc5sy33u8uxo4igf0oacugmv FOREIGN KEY (created_by_user_id)  REFERENCES public."user"(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.group_membership ADD CONSTRAINT fkqxaox5n0l3y9obsaqdmy1xccn FOREIGN KEY (updated_by_user_id)  REFERENCES public."user"(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN ALTER TABLE public.join_request     ADD CONSTRAINT fkhyogh43uuahrt1lf4do24ldw2 FOREIGN KEY (squad_id)           REFERENCES public.squad(id);           EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.join_request     ADD CONSTRAINT fkt6yyiyodmswdf6yys4j2tcepg FOREIGN KEY (user_id)            REFERENCES public."user"(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.join_request     ADD CONSTRAINT fktnop1uee7i3t3qbxswgk1poal FOREIGN KEY (reviewed_by_user_id) REFERENCES public."user"(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.join_request     ADD CONSTRAINT fkbfulef736rc69ah0s6yu7n6ld FOREIGN KEY (created_by_user_id)  REFERENCES public."user"(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.join_request     ADD CONSTRAINT fkl7ut3cfkwq0gp3jsa59xyah93 FOREIGN KEY (updated_by_user_id)  REFERENCES public."user"(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN ALTER TABLE public.squad_request    ADD CONSTRAINT fkngu1c7mtuu12d6etulcb9g5js FOREIGN KEY (requested_by_user_id) REFERENCES public."user"(id);         EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.squad_request    ADD CONSTRAINT fk3g80qj2dyxr3rtk3tgpjbn8fc FOREIGN KEY (reviewed_by_user_id) REFERENCES public."user"(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.squad_request    ADD CONSTRAINT fk4arwsvcta1ivuvwr2ci96m4w5 FOREIGN KEY (created_by_user_id)  REFERENCES public."user"(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.squad_request    ADD CONSTRAINT fkn68txgggbf9t4eh9qgt7r1bym FOREIGN KEY (updated_by_user_id)  REFERENCES public."user"(id);          EXCEPTION WHEN duplicate_object THEN NULL; END $$;
