name: Deploy to VPS

on:
  push:
    branches:
      - master  # Master branch'e push yapıldığında çalıştır

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Connection and Run Deploy Script
        run: |
          echo "${{ secrets.VPS_SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key serkanursavas@147.93.126.10 -p 2222 "cd /home/serkanursavas/projects/springboot/my-backend/404-backend && ./deploy.sh"