name: Deploy to VPS

on:
  push:
    branches:
      - master  # Ana branch değiştirildiğinde çalışacak

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Connection
        run: |
          echo "${{ secrets.VPS_SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key serkanursavas@147.93.126.10 -p 2222 "echo Bağlantı başarılı!"